# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    lp_user.registration_listener:
        class: UserBundle\EventListener\RegistrationListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
    lp_user.login_handler:
        class:  UserBundle\Handlers\LoginSuccessHandler
        arguments:  ['@security.authorization_checker', '@router']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    lp_user_form_registration:
        class: UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: lp_user_registration }
    lp_EntidadManager:
        class: AppBundle\Services\EntidadManager\EntidadManager
        arguments:    [ "@doctrine.orm.entity_manager", "@security.token_storage", "@form.factory" ]                           
