truncate entidad_nacionalidad;
/* Data for table "entidad_nacionalidad" */
INSERT INTO entidad_nacionalidad (id, codigo, nombre, `status`) VALUES
  (1, 'ARGENTINA', 'Argentina', 0),
  (2, 'AFGANISTÁN', 'Afganistán', 0),
  (3, 'ALBANIA', 'Albania', 0),
  (4, 'ALEMANIA', 'Alemania', 0),
  (5, 'ANDORRA', 'Andorra', 0),
  (6, 'ANGOLA', 'Angola', 0),
  (7, 'ANTIGUA Y BARBUDA', 'Antigua y Barbuda', 0),
  (8, 'ARABIA SAUDITA', 'Arabia Saudita', 0),
  (9, 'ARGELIA', 'Argelia', 0),
  (10, 'ARMENIA', 'Armenia', 0),
  (11, 'AUSTRALIA', 'Australia', 0),
  (12, 'AUSTRIA', 'Austria', 0),
  (13, 'AZERBAIYÁN', 'Azerbaiyán', 0),
  (14, 'BAHAMAS', 'Bahamas', 0),
  (15, 'BANGLADÉS', 'Bangladés', 0),
  (16, 'BARBADOS', 'Barbados', 0),
  (17, 'BARÉIN', 'Baréin', 0),
  (18, 'BÉLGICA', 'Bélgica', 0),
  (19, 'BELICE', 'Belice', 0),
  (20, 'BENÍN', 'Benín', 0),
  (21, 'BIELORRUSIA', 'Bielorrusia', 0),
  (22, 'BIRMANIA', 'Birmania', 0),
  (23, 'BOLIVIA', 'Bolivia', 0),
  (24, 'BOSNIA Y HERZEGOVINA', 'Bosnia y Herzegovina', 0),
  (25, 'BOTSUANA', 'Botsuana', 0),
  (26, 'BRASIL', 'Brasil', 0),
  (27, 'BRUNÉI', 'Brunéi', 0),
  (28, 'BULGARIA', 'Bulgaria', 0),
  (29, 'BURKINA FASO', 'Burkina Faso', 0),
  (30, 'BURUNDI', 'Burundi', 0),
  (31, 'BUTÁN', 'Bután', 0),
  (32, 'CABO VERDE', 'Cabo Verde', 0),
  (33, 'CAMBOYA', 'Camboya', 0),
  (34, 'CAMERÚN', 'Camerún', 0),
  (35, 'CANADÁ', 'Canadá', 0),
  (36, 'CATAR', 'Catar', 0),
  (37, 'CHAD', 'Chad', 0),
  (38, 'CHILE', 'Chile', 0),
  (39, 'CHINA', 'China', 0),
  (40, 'CHIPRE', 'Chipre', 0),
  (41, 'CIUDAD DEL VATICANO', 'Ciudad del Vaticano', 0),
  (42, 'COLOMBIA', 'Colombia', 0),
  (43, 'COMORAS', 'Comoras', 0),
  (44, 'COREA DEL NORTE', 'Corea del Norte', 0),
  (45, 'COREA DEL SUR', 'Corea del Sur', 0),
  (46, 'COSTA DE MARFIL', 'Costa de Marfil', 0),
  (47, 'COSTA RICA', 'Costa Rica', 0),
  (48, 'CROACIA', 'Croacia', 0),
  (49, 'CUBA', 'Cuba', 0),
  (50, 'DINAMARCA', 'Dinamarca', 0),
  (51, 'DOMINICA', 'Dominica', 0),
  (52, 'ECUADOR', 'Ecuador', 0),
  (53, 'EGIPTO', 'Egipto', 0),
  (54, 'EL SALVADOR', 'El Salvador', 0),
  (55, 'EMIRATOS ÁRABES UNIDOS', 'Emiratos Árabes Unidos', 0),
  (56, 'ERITREA', 'Eritrea', 0),
  (57, 'ESLOVAQUIA', 'Eslovaquia', 0),
  (58, 'ESLOVENIA', 'Eslovenia', 0),
  (59, 'ESPAÑA', 'España', 0),
  (60, 'ESTADOS UNIDOS', 'Estados Unidos', 0),
  (61, 'ESTONIA', 'Estonia', 0),
  (62, 'ETIOPÍA', 'Etiopía', 0),
  (63, 'FILIPINAS', 'Filipinas', 0),
  (64, 'FINLANDIA', 'Finlandia', 0),
  (65, 'FIYI', 'Fiyi', 0),
  (66, 'FRANCIA', 'Francia', 0),
  (67, 'GABÓN', 'Gabón', 0),
  (68, 'GAMBIA', 'Gambia', 0),
  (69, 'GEORGIA', 'Georgia', 0),
  (70, 'GHANA', 'Ghana', 0),
  (71, 'GRANADA', 'Granada', 0),
  (72, 'GRECIA', 'Grecia', 0),
  (73, 'GUATEMALA', 'Guatemala', 0),
  (74, 'GUINEA ECUATORIAL', 'Guinea ecuatorial', 0),
  (75, 'GUINEA', 'Guinea', 0),
  (76, 'GUINEA-BISÁU', 'Guinea-Bisáu', 0),
  (77, 'GUYANA', 'Guyana', 0),
  (78, 'HAITÍ', 'Haití', 0),
  (79, 'HONDURAS', 'Honduras', 0),
  (80, 'HUNGRÍA', 'Hungría', 0),
  (81, 'INDIA', 'India', 0),
  (82, 'INDONESIA', 'Indonesia', 0),
  (83, 'IRAK', 'Irak', 0),
  (84, 'IRÁN', 'Irán', 0),
  (85, 'IRLANDA', 'Irlanda', 0),
  (86, 'ISLANDIA', 'Islandia', 0),
  (87, 'ISLAS MARSHALL', 'Islas Marshall', 0),
  (88, 'ISLAS SALOMÓN', 'Islas Salomón', 0),
  (89, 'ISRAEL', 'Israel', 0),
  (90, 'ITALIA', 'Italia', 0),
  (91, 'JAMAICA', 'Jamaica', 0),
  (92, 'JAPÓN', 'Japón', 0),
  (93, 'JORDANIA', 'Jordania', 0),
  (94, 'KAZAJISTÁN', 'Kazajistán', 0),
  (95, 'KENIA', 'Kenia', 0),
  (96, 'KIRGUISTÁN', 'Kirguistán', 0),
  (97, 'KIRIBATI', 'Kiribati', 0),
  (98, 'KUWAIT', 'Kuwait', 0),
  (99, 'LAOS', 'Laos', 0),
  (100, 'LESOTO', 'Lesoto', 0),
  (101, 'LETONIA', 'Letonia', 0),
  (102, 'LÍBANO', 'Líbano', 0),
  (103, 'LIBERIA', 'Liberia', 0),
  (104, 'LIBIA', 'Libia', 0),
  (105, 'LIECHTENSTEIN', 'Liechtenstein', 0),
  (106, 'LITUANIA', 'Lituania', 0),
  (107, 'LUXEMBURGO', 'Luxemburgo', 0),
  (108, 'MADAGASCAR', 'Madagascar', 0),
  (109, 'MALASIA', 'Malasia', 0),
  (110, 'MALAUI', 'Malaui', 0),
  (111, 'MALDIVAS', 'Maldivas', 0),
  (112, 'MALÍ', 'Malí', 0),
  (113, 'MALTA', 'Malta', 0),
  (114, 'MARRUECOS', 'Marruecos', 0),
  (115, 'MAURICIO', 'Mauricio', 0),
  (116, 'MAURITANIA', 'Mauritania', 0),
  (117, 'MÉXICO', 'México', 0),
  (118, 'MICRONESIA', 'Micronesia', 0),
  (119, 'MOLDAVIA', 'Moldavia', 0),
  (120, 'MÓNACO', 'Mónaco', 0),
  (121, 'MONGOLIA', 'Mongolia', 0),
  (122, 'MONTENEGRO', 'Montenegro', 0),
  (123, 'MOZAMBIQUE', 'Mozambique', 0),
  (124, 'NAMIBIA', 'Namibia', 0),
  (125, 'NAURU', 'Nauru', 0),
  (126, 'NEPAL', 'Nepal', 0),
  (127, 'NICARAGUA', 'Nicaragua', 0),
  (128, 'NÍGER', 'Níger', 0),
  (129, 'NIGERIA', 'Nigeria', 0),
  (130, 'NORUEGA', 'Noruega', 0),
  (131, 'NUEVA ZELANDA', 'Nueva Zelanda', 0),
  (132, 'OMÁN', 'Omán', 0),
  (133, 'PAÍSES BAJOS', 'Países Bajos', 0),
  (134, 'PAKISTÁN', 'Pakistán', 0),
  (135, 'PALAOS', 'Palaos', 0),
  (136, 'PANAMÁ', 'Panamá', 0),
  (137, 'PAPÚA NUEVA GUINEA', 'Papúa Nueva Guinea', 0),
  (138, 'PARAGUAY', 'Paraguay', 0),
  (139, 'PERÚ', 'Perú', 0),
  (140, 'POLONIA', 'Polonia', 0),
  (141, 'PORTUGAL', 'Portugal', 0),
  (142, 'REINO UNIDO', 'Reino Unido', 0),
  (143, 'REPÚBLICA CENTROAFRICANA', 'República Centroafricana', 0),
  (144, 'REPÚBLICA CHECA', 'República Checa', 0),
  (145, 'REPÚBLICA DE MACEDONIA', 'República de Macedonia', 0),
  (146, 'REPÚBLICA DEL CONGO', 'República del Congo', 0),
  (147, 'REPÚBLICA DEMOCRÁTICA DEL CONGO', 'República Democrática del Congo', 0),
  (148, 'REPÚBLICA DOMINICANA', 'República Dominicana', 0),
  (149, 'REPÚBLICA SUDAFRICANA', 'República Sudafricana', 0),
  (150, 'RUANDA', 'Ruanda', 0),
  (151, 'RUMANÍA', 'Rumanía', 0),
  (152, 'RUSIA', 'Rusia', 0),
  (153, 'SAMOA', 'Samoa', 0),
  (154, 'SAN CRISTÓBAL Y NIEVES', 'San Cristóbal y Nieves', 0),
  (155, 'SAN MARINO', 'San Marino', 0),
  (156, 'SAN VICENTE Y LAS GRANADINAS', 'San Vicente y las Granadinas', 0),
  (157, 'SANTA LUCÍA', 'Santa Lucía', 0),
  (158, 'SANTO TOMÉ Y PRÍNCIPE', 'Santo Tomé y Príncipe', 0),
  (159, 'SENEGAL', 'Senegal', 0),
  (160, 'SERBIA', 'Serbia', 0),
  (161, 'SEYCHELLES', 'Seychelles', 0),
  (162, 'SIERRA LEONA', 'Sierra Leona', 0),
  (163, 'SINGAPUR', 'Singapur', 0),
  (164, 'SIRIA', 'Siria', 0),
  (165, 'SOMALIA', 'Somalia', 0),
  (166, 'SRI LANKA', 'Sri Lanka', 0),
  (167, 'SUAZILANDIA', 'Suazilandia', 0),
  (168, 'SUDÁN DEL SUR', 'Sudán del Sur', 0),
  (169, 'SUDÁN', 'Sudán', 0),
  (170, 'SUECIA', 'Suecia', 0),
  (171, 'SUIZA', 'Suiza', 0),
  (172, 'SURINAM', 'Surinam', 0),
  (173, 'TAILANDIA', 'Tailandia', 0),
  (174, 'TANZANIA', 'Tanzania', 0),
  (175, 'TAYIKISTÁN', 'Tayikistán', 0),
  (176, 'TIMOR ORIENTAL', 'Timor Oriental', 0),
  (177, 'TOGO', 'Togo', 0),
  (178, 'TONGA', 'Tonga', 0),
  (179, 'TRINIDAD Y TOBAGO', 'Trinidad y Tobago', 0),
  (180, 'TÚNEZ', 'Túnez', 0),
  (181, 'TURKMENISTÁN', 'Turkmenistán', 0),
  (182, 'TURQUÍA', 'Turquía', 0),
  (183, 'TUVALU', 'Tuvalu', 0),
  (184, 'UCRANIA', 'Ucrania', 0),
  (185, 'UGANDA', 'Uganda', 0),
  (186, 'URUGUAY', 'Uruguay', 0),
  (187, 'UZBEKISTÁN', 'Uzbekistán', 0),
  (188, 'VANUATU', 'Vanuatu', 0),
  (189, 'VENEZUELA', 'Venezuela', 0),
  (190, 'VIETNAM', 'Vietnam', 0),
  (191, 'YEMEN', 'Yemen', 0),
  (192, 'YIBUTI', 'Yibuti', 0),
  (193, 'ZAMBIA', 'Zambia', 0),
  (194, 'ZIMBABUE', 'Zimbabue', 0);
