INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'1','Accidente de Trabajo (Art. 1113 C. Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'2','Accidente de Trabajo (Ley 9.688)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'3','Acción Confesoria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'4','Acción de Fraude (Art. 1298 C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'5','Acción de Inconstitucionalidad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'6','Acción de Nulidad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'7','Acción de Reducción','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'8','Acción Declarativa (Art. 322 C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'9','Acción Negatoria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'10','Acción Posesoria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'11','Accion Reivindicatoria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'12','Acción Subrogatoria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'13','Acreditación de Vínculo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'14','Actualización de Legado','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'15','Administración de Bienes','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'16','Adopción','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'17','Afectación al Régimen de la Ley 19.724','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'18','Alimentos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'19','Alimentos y Litis Expensas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'20','Alimentos y tenencia','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'21','Alimentos: aumento y cese de cuota','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'22','Amparo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'23','Apelación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'24','Apremio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'25','Aseguramiento de bienes','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'26','Asesoramiento','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'27','Ausencia con Presunción de Fallecimiento','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'28','Ausencia Simple','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'29','Autorización','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'30','Autorización para mantenimiento de apellido','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'31','Beneficio de litigar sin gastos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'32','Cancelación de Hipoteca','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'33','Cesación de cuota alimentaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'34','Cesión de Derechos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'35','Cobranza de alquiler','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'36','Cobro de Alquileres','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'37','Cobro de Astreintes','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'38','Cobro de Australes','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'39','Cobro de Honorarios','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'40','Cobro de Medianería','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'41','Cobro de Suma de Dinero','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'42','Cobro de Valor Locativo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'43','Cobro Ejecutivo de Expensas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'44','Colación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'45','Concurso Preventivo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'46','Consignación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'47','Consignación de alimentos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'48','Consignación de Alquileres','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'49','Consignación de Cosas Muebles','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'50','Consignación de Expensas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'51','Consignación de Llaves','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'52','Conversión en divoricio vincular','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'53','Convocatoria de Acreedores','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'54','Convocatoria de Asamblea','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'55','Copia y Renovación de Títulos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'56','Cuestiones de Vecindad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'57','Cumplimiento de Contrato','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'58','Cumplimiento de funciones del tutor','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'59','Cumplimiento de Legado','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'60','Cumplimiento de Reglamento de Copropiedad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'61','Curatela (art. 12 C. Penal)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'62','Curatela Especial','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'63','Daños y Perjuicios','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'64','Daños y Perjuicios (CUADERNO PRUEBA ACTORA)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'65','Daños y Perjuicios (CUADERNO PRUEBA DEMANDADA)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'66','Defraudación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'67','Denuncia','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'68','Denuncia de Daño Temido','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'69','Denuncia del Registro Civil y Capacidad de las personas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'70','Depositó de obra','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'71','Derecho de Acrecer','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'72','Derecho de Servidumbres en General','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'73','Derecho de Uso y Habitación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'74','Derecho de Usufructo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'75','Desafectación de Bien de familia','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'76','Desalojo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'77','Desalojo por Falta de Pago','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'78','Desalojo por Vencimiento de Contrato','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'79','Despido','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'80','Dictamen','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'81','Diligencia Preliminar','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'82','Disolución de Sociedad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'83','Disolución de Sociedad de Hecho','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'84','Div.Cond.(Incidente cobro pesos por utilización exclusiva)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'85','División de Condominio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'86','Divorcio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'87','Divorcio  (art. 215 C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'88','Divorcio Vincular Contradictorio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'89','Divorcio Vincular por presentación conjunta','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'90','Divorcio y Exclusión de conyuge','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'91','Divorcio y Tenencia de Hijos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'92','Divoricio y Alimentos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'93','Divoricio, Alimentos y Tenencia de Hijos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'94','Ejecución de Alimentos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'95','Ejecución de Alquileres','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'96','Ejecución de Convenio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'97','Ejecución de Expensas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'98','Ejecución de Honorarios','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'99','Ejecución de Sentencia','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'100','Ejecución Fiscal','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'101','Ejecución Hipotecaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'102','Ejecución Prendaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'103','Ejecutivo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'104','Ejercicio de la Patria Potestad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'105','Encubrimiento','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'106','Entrega de Legado','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'107','Escrituración','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'108','Evicción','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'109','Exámen de Los Liros por el Socio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'110','Exclusión  de la herencia','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'111','Exequatur y Reconocimiento de Sentencia Extranjera','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'112','Exhorto','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'113','Expropiación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'114','Expropiación Inversa','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'115','Externación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'116','Extinción de contrato de trabajo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'117','Extrajudiciales','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'118','Fijación de Plazo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'119','Fijación de régimen de visitas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'120','Fijación de valor locativo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'121','Filiación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'122','Guarda','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'123','Hallazgo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'124','Homicidio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'125','Homicidio Culposo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'126','Homologación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'127','Homologación de convenio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'128','Hurto','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'129','Impugnación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'130','Impugnación de maternidad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'131','Impugnación de paternidad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'132','Impugnación de Testamento','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'133','Incidente aumento cuota alimentaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'134','Incidente de liquidación de Soc.Conyugal','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'135','Incidente de retitución de inmueble','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'136','Incidente de Verificación de Crédito','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'137','Incidente ejecución convenio de alimentos.','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'138','Incidente ejecución honorarios','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'139','Incidente Embargo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'140','Incidente Exclusión del Hogar','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'141','Incidente exclusión vocación hereditaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'142','Incidente reducción cuota alimentos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'143','Incidente rendicion de cuentas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'144','Inclusión de Bienes','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'145','Información Sumaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'146','Información sumaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'147','Información Sumaria Ley 10.996','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'148','Inhabilitación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'149','Inhabilitación (art. 152 bis inc 3º C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'150','Inhibitoria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'151','Insania','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'152','Inscripcción de Automotor','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'153','Inscripción','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'154','Inscripción de nacimiento','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'155','Interdicto de adquirir','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'156','Interdicto de obra nueva','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'157','Interdicto de recobrar','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'158','Interdicto de retener','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'159','Interdicto salida del país de hijos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'160','Interrupción de Prescripción (Art. 3986 C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'161','Juicio arbitral','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'162','Juicio de Amigables Componedores','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'163','Juicio Pericial','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'164','Lesiones','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'165','Levantamiento de Embargo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'166','Liquidación de Sociedad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'167','Liquidación de Sociedad Conyugal','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'168','Litis Expensas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'169','Locación de Obra','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'170','Locación de Servicios','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'171','Medianería','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'172','Medida Autosatisfactiva','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'173','Medidas Cautelares','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'174','Medidas Precautorias (art. 231 C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'175','Medidas Precautorias (art. 233 C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'176','Medidas Preliminares','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'177','Medidas Previas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'178','Mensura y Deslinde','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'179','Modificación del Reglamento de Copropiedad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'180','Muerte dudosa','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'181','Muerte por accidente ferroviario','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'182','Nulidad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'183','Nulidad de Acto Administrativo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'184','Nulidad de Acto Jurídico','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'185','Nulidad de Adopción','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'186','Nulidad de Asamblea','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'187','Nulidad de Cláusulas Contractuales','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'188','Nulidad de Contrato','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'189','Nulidad de Convenio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'190','Nulidad de Escritura','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'191','Nulidad de Inscripción','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'192','Nulidad de Matrimonio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'193','Nulidad de Resolción Municipal','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'194','Nulidad de Testamento','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'195','Oposición a solicitud de Marcas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'196','Ordinario','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'197','Partición de Herencia','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'198','Patentamiento','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'199','Pérdida de administración de bienes','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'200','Pérdida de vocación hereditaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'201','Pericia arbitral','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'202','Petición de Herencia','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'203','Posesión Decenal','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'204','Posesión Vicenal','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'205','Preparación de la vía ejecutiva','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'206','Prescripción','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'207','Prescripción (art. 4.023 C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'208','Prescripción (art. 4.027 C.Civil inc.3º)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'209','Prescripción (art. 4.032 C.Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'210','Prescripción adquisitiva','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'211','Privación de la Patria Potestad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'212','Privación de visita','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'213','Procesos Informativos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'214','Propiedad intelectual (Ley 11.723)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'215','Protección de persona','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'216','Protocolización de Testamento','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'217','Quiebra','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'218','Reajuste de convenio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'219','Reconciliación (art. 234 Ley 23.515)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'220','Reconocimiento de la calidad de socio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'221','Reconocimiento de la categoría autoral','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'222','Reconocimiento de Mercaderias','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'223','Rectificación de título de propiedad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'224','Redacción de contrato','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'225','Redargución de falsedad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'226','Reducción de precio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'227','Reducción de valor locativo (art. 5º Ley 23.747)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'228','Régimen de visitas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'229','Registro de Marcas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'230','Regulación de honorarios','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'231','Rehabilitación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'232','Reintegro','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'233','Reintegro de hijo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'234','Reinvindicación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'235','Remoción de administrador','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'236','Rendición de Cuentas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'237','Repetición','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'238','Rescisión','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'239','Resolución de Contrato','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'240','Restitución de Comodato','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'241','Retiro Policial','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'242','Retrocesión','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'243','Revocación de acto jurídico','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'244','Revocación de adopción','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'245','Revocación de donaciones','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'246','Robo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'247','Robo y Abuso de Armas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'248','Separación personal','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'249','Separación personal (art. 205 C. Civil)','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'250','Separación personal y alimentos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'251','Separación personal y exclusión de conyuge','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'252','Separación personal y tenencia de hijos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'253','Separación personal, alimentos y tenencia','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'254','Simulación','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'255','Sucesión ab intestato','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'256','Sucesión Testamentaria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'257','Sucesión vacante','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'258','Suicidio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'259','Sumario','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'260','Sumarísimo','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'261','Suspensión de la Patria Potestad','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'262','Suspensión de régimen de visitas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'263','temporal','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'264','Tenencia de hijos','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'265','Tenencia de hijos y régimen de visitas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'266','Tentativa de Homicidio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'267','Tercería de Dominio','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'268','Tercería de mejor derecho','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'269','Transferencia de automotor','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'270','Transferencia de Marcas','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'271','Tutela','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'272','Tutela especial','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'273','Usucapión','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'274','Usurpación de títulos y honores','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'275','Venia supletoria','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'276','Venta de Mercaderias','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'277','Verificación de Crédito','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'278','Vicios redhibitorios','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'279','Víctima de Hurto','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'280','Violación Art. 146 CP.','',0,0);
INSERT INTO tipo_proceso (id_estudio, codigo, nombre, descripcion, esp, `status`) Values ($id_estudio,'281','Violación con alevosía','',0,0);